In [104]:
import numpy as np
nums,*data = open(r"\adventday4.txt", "r")
nums = np.loadtxt(nums.split(','),int)
data = np.loadtxt(data,int).reshape(-1,5,5)

In [381]:
def bingo(nums,data):
    state = data.dot(0)
    for i in range(len(nums)):
            if nums[i] in data:
                loc = np.array(np.where(data==nums[i]))
                for k in range(loc.shape[1]):
                    state[loc[0][k],loc[1][k],loc[2][k]] = 1
            for h in range(len(data)):
                for l in range(len(data[0])):
                    rowsum = np.sum(state[h][l])
                    colsum = np.sum(state[h][:,l])
                    if rowsum == 5 or colsum == 5:
                        print("winning board is {0} after {1} numbers".format(h,i))
                        return(data[h],state[h],nums[i])

In [390]:
board,statewin,lnum = bingo(nums,data)
board,statewin
zeros = np.where(statewin==0)
sum = 0
for i in range(len(zeros[0])):
    sum += board[zeros[0][i],zeros[1][i]]
    
sum*lnum

winning board is 68 after 15 numbers


41668

In [352]:
def p2(nums,data):
    state = data.dot(0)
    for i in range(len(nums)):
            if nums[i] in data:
                loc = np.array(np.where(data==nums[i]))
                for k in range(loc.shape[1]):
                    state[loc[0][k],loc[1][k],loc[2][k]] = 1
            winners = []
            for h in range(len(data)):
                for l in range(len(data[0])):
                    rowsum = np.sum(state[h][l])
                    colsum = np.sum(state[h][:,l])
                    
                    if rowsum == 5 or colsum == 5:
                        winners.append(h)
                        if (100-len(set(winners))) ==1:
                            for u in range(100):
                                if u not in set(winners):
                                    print(u)
                                    return(u)

In [392]:
board,statewin,lnum = bingo_loss(nums,data[14])
board,statewin
zeros = np.where(statewin==0)
print(board,statewin,lnum)
sum = 0
for i in range(len(zeros[0])):
    sum += board[zeros[0][i],zeros[1][i]]
    
sum*lnum

winning board is 0 after 83 numbers
[[26 47  2 22  9]
 [ 6 81 53 17 88]
 [58 25 55 31 19]
 [42 27 85 97 14]
 [64 52 66 63 51]] [[1 1 1 1 0]
 [1 0 1 1 1]
 [0 0 1 1 1]
 [1 1 0 1 0]
 [1 1 0 1 1]] 31


10478

In [388]:
def bingo_loss(nums,data):
    state = data.dot(0)
    for i in range(len(nums)):
            if nums[i] in data:
                loc = np.array(np.where(data==nums[i]))
                for k in range(loc.shape[1]):
                    state[loc[0][k],loc[1][k]] = 1
            for h in range(len(data)):
                for l in range(len(data[0])):
                    rowsum = np.sum(state[h][l])
                    colsum = np.sum(state[:,l])
                    if rowsum == 5 or colsum == 5:
                        print("winning board is {0} after {1} numbers".format(h,i))
                        return(data,state,nums[i])